### ISSUE TITLE
项目开发环境问题 (lein repl start project failed with java exception...)

### ISSUE THREAD

**Issue by stardiviner** [PromptlyCode/PromptlyCode#2]
Versions info:

#+BEGIN_SRC shell
lein --version
#+END_SRC

#+RESULTS:
: Leiningen 2.7.1 on Java 1.8.0_102 Java HotSpot(TM) 64-Bit Server VM

Clojure version: ~[org.clojure/clojure "1.9.0-alpha17"]~

#+BEGIN_EXAMPLE
lein repl # in xunfei-clj/examples/hello-xunfei/ dir.
#+END_EXAMPLE

#+BEGIN_EXAMPLE
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2183)
        at clojure.lang.RT.classForName(RT.java:2192)
        at clojure.lang.RT.loadClassForName(RT.java:2211)
        at clojure.lang.RT.load(RT.java:445)
        at clojure.lang.RT.load(RT.java:421)
        at clojure.lang.RT.doInit(RT.java:463)
        at clojure.lang.RT.<clinit>(RT.java:333)
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: import in this context, compiling:(clojure/core_instant18.clj:11:1)
        at clojure.lang.Compiler.analyze(Compiler.java:6748)
        at clojure.lang.Compiler.analyze(Compiler.java:6685)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3787)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6948)
        at clojure.lang.Compiler.analyze(Compiler.java:6729)
        at clojure.lang.Compiler.analyze(Compiler.java:6685)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6056)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5428)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3993)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6944)
        at clojure.lang.Compiler.analyze(Compiler.java:6729)
        at clojure.lang.Compiler.eval(Compiler.java:7002)
        at clojure.lang.Compiler.load(Compiler.java:7457)
        at clojure.lang.RT.loadResourceScript(RT.java:374)
        at clojure.lang.RT.loadResourceScript(RT.java:365)
        at clojure.lang.RT.load(RT.java:455)
        at clojure.lang.RT.load(RT.java:421)
        at clojure.core$load$fn__6368.invoke(core.clj:6008)
        at clojure.core$load.invokeStatic(core.clj:6007)
        at clojure.core$load.doInvoke(core.clj:5991)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$fn__7857.invokeStatic(core.clj:6664)
        at clojure.core$fn__7857.invoke(core.clj:6662)
        at clojure.core__init.load(Unknown Source)
        at clojure.core__init.<clinit>(Unknown Source)
        ... 10 more
Caused by: java.lang.RuntimeException: Unable to resolve symbol: import in this context
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler.resolveIn(Compiler.java:7242)
        at clojure.lang.Compiler.resolve(Compiler.java:7186)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7147)
        at clojure.lang.Compiler.analyze(Compiler.java:6708)
        ... 34 more
Exception in thread "Thread-3" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
        at clojure.core$ex_info.invokeStatic(core.clj:4617)
        at clojure.core$ex_info.invoke(core.clj:4617)
        at leiningen.core.eval$fn__5732.invokeStatic(eval.clj:264)
        at leiningen.core.eval$fn__5732.invoke(eval.clj:260)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:366)
        at leiningen.core.eval$eval_in_project.invoke(eval.clj:356)
        at leiningen.repl$server$fn__11838.invoke(repl.clj:243)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:650)
        at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
REPL server launch timed out.
#+END_EXAMPLE

**Comment by stardiviner** [comment]
Problem fixed after I disable some dependencies in Leiningen global profiles.clj.

**Comment by xlisp** [comment]
👍  @stardiviner

**Comment by xlisp** [comment]
@stardiviner  你装了cider了吗？先跑起来语音朗读和识别先, 再用cider连接项目的repl

**Comment by stardiviner** [comment]
嗯，正在弄，估计要明天会搞定。我同时在折腾Okular打开epub文件失败的bug，Arch Linux platform dependent.

**Comment by xlisp** [comment]
这个项目在Linux能跑，前提是你的音频驱动和录音驱动可以使用

**Comment by stardiviner** [comment]
插个题外话，你试过现在挺火的一个语音助手项目Mycroft么？

**Comment by xlisp** [comment]
国内做得最好的语音识别技术就是讯飞了，没有第二个. 这件事情我鉴定过了呀

**Comment by stardiviner** [comment]
不是国内的。国外的。和其他的集成也挺不错。比如KDE桌面环境下还有widget。挺方便。了解下就好。

**Comment by stardiviner** [comment]
莫非你voice-literate-programming要用中文语音？

**Comment by stardiviner** [comment]
咱们不在这里聊这个了，切到其他聊天器里吧？比如微信，我的是stardiviner. 你加我后，我会删除这条消息。

**Comment by xlisp** [comment]
语音识别,中文的更容易做, 英文不好做. 目前就是支持中文,不支持英文. 如果用英文的话, 国外比讯飞做得好的很多呀
